### ISSUE TITLE
Not showing proper alert

### ISSUE THREAD

**Issue by AyusGup** [coderSuresh/alert-for-web#4]
![image](https://github.com/coderSuresh/alert-for-web/assets/127961367/4355d0a7-941d-4855-8b02-5a588bd2c0e7)

the alert is always showing same alert text in all 3 cases.

please assign this issue to me under hacktoberfest  label

**Comment by coderSuresh** [comment]
Please go ahead. You can fix the issue and create a pull request.

**Comment by AyusGup** [comment]
@coderSuresh kindly add hacktoberfest, hacktoberfest-accepted label to my issue else it wouldn't be counted as my contribution in hacktoberfest
